name: karee_inject
version: 1.0.4+1
description: Part of Karee that manage all annotation used to inject dependency
repository: https://github.com/ChamplainLeCode/karee_inject

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  meta: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
