name: karee_inject
description: Part of Karee that manage all annotation used to inject dependency
version: 1.0.1
homepage: https://github.com/ChamplainLeCode/karee_inject

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  reflectable: ^3.0.1
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  build_runner:
  test: ^1.14.4
