name: karee_inject
version: 1.0.3+2
description: Part of Karee that manage all annotation used to inject dependency
repository: https://github.com/champlainlecode/karee_inject

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
