name: karee_inject
description: Part of Karee that manage all annotation used to inject dependency
version: 1.0.3
homepage: https://github.com/ChamplainLeCode/karee_inject.git

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
